### ISSUE TITLE
Can't find Pipfile while building

### ISSUE THREAD

**Issue by VannTen** [asyncon/setuptools-pipfile#4]
Hi. I'm trying to use this and run into the following error: 

<details>

```console
pyproject-build 
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools, setuptools-pipfile, wheel)
* Getting build dependencies for sdist...
/tmp/build-env-rvbir7kl/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
No `packages` or `py_modules` configuration, performing automatic discovery.
`flat-layout` detected -- analysing .
discovered packages -- ['thoth', 'thoth.package_extract', 'thoth.package_extract.bin']
running egg_info
writing thoth_package_extract.egg-info/PKG-INFO
writing dependency_links to thoth_package_extract.egg-info/dependency_links.txt
writing entry points to thoth_package_extract.egg-info/entry_points.txt
writing requirements to thoth_package_extract.egg-info/requires.txt
writing top-level names to thoth_package_extract.egg-info/top_level.txt
reading manifest file 'thoth_package_extract.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'thoth_package_extract.egg-info/SOURCES.txt'
* Building sdist...
/tmp/build-env-rvbir7kl/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
No `packages` or `py_modules` configuration, performing automatic discovery.
`flat-layout` detected -- analysing .
discovered packages -- ['thoth', 'thoth.package_extract', 'thoth.package_extract.bin']
running sdist
running egg_info
writing thoth_package_extract.egg-info/PKG-INFO
writing dependency_links to thoth_package_extract.egg-info/dependency_links.txt
writing entry points to thoth_package_extract.egg-info/entry_points.txt
writing requirements to thoth_package_extract.egg-info/requires.txt
writing top-level names to thoth_package_extract.egg-info/top_level.txt
reading manifest file 'thoth_package_extract.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'thoth_package_extract.egg-info/SOURCES.txt'
running check
creating thoth-package-extract-1.3.1
creating thoth-package-extract-1.3.1/thoth
creating thoth-package-extract-1.3.1/thoth/package_extract
creating thoth-package-extract-1.3.1/thoth/package_extract/bin
creating thoth-package-extract-1.3.1/thoth_package_extract.egg-info
copying files to thoth-package-extract-1.3.1...
copying LICENSE -> thoth-package-extract-1.3.1
copying README.rst -> thoth-package-extract-1.3.1
copying pyproject.toml -> thoth-package-extract-1.3.1
copying thoth/package_extract/__init__.py -> thoth-package-extract-1.3.1/thoth/package_extract
copying thoth/package_extract/cli.py -> thoth-package-extract-1.3.1/thoth/package_extract
copying thoth/package_extract/core.py -> thoth-package-extract-1.3.1/thoth/package_extract
copying thoth/package_extract/exceptions.py -> thoth-package-extract-1.3.1/thoth/package_extract
copying thoth/package_extract/image.py -> thoth-package-extract-1.3.1/thoth/package_extract
copying thoth/package_extract/rpmlib.py -> thoth-package-extract-1.3.1/thoth/package_extract
copying thoth/package_extract/bin/skopeo -> thoth-package-extract-1.3.1/thoth/package_extract/bin
copying thoth_package_extract.egg-info/PKG-INFO -> thoth-package-extract-1.3.1/thoth_package_extract.egg-info
copying thoth_package_extract.egg-info/SOURCES.txt -> thoth-package-extract-1.3.1/thoth_package_extract.egg-info
copying thoth_package_extract.egg-info/dependency_links.txt -> thoth-package-extract-1.3.1/thoth_package_extract.egg-info
copying thoth_package_extract.egg-info/entry_points.txt -> thoth-package-extract-1.3.1/thoth_package_extract.egg-info
copying thoth_package_extract.egg-info/requires.txt -> thoth-package-extract-1.3.1/thoth_package_extract.egg-info
copying thoth_package_extract.egg-info/top_level.txt -> thoth-package-extract-1.3.1/thoth_package_extract.egg-info
Writing thoth-package-extract-1.3.1/setup.cfg
Creating tar archive
removing 'thoth-package-extract-1.3.1' (and everything under it)
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools, setuptools-pipfile, wheel)
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools/dist.py", line 475, in __init__
    _Distribution.__init__(
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools/dist.py", line 899, in finalize_options
    ep(self)
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools_pipfile/keyword.py", line 48, in finalize_dist
    use_pipfile(dist, None, value)
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools_pipfile/keyword.py", line 32, in use_pipfile
    pipfile = Pipfile(path, interpolate, pythons, extras, indexes)
  File "/tmp/build-env-1040vlhf/lib/python3.10/site-packages/setuptools_pipfile/pipfile.py", line 162, in __init__
    with open(self.path, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'Pipfile'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

</details>

My pyproject.toml looks like this :
```toml
[project]
name = "thoth-package-extract"
description = "Tool and library for extracting packages from a docker build log"
license = {file = "LICENSE"}

...

[project.scripts]
thoth-package-extract = "thoth.package_extract.cli:cli"

[build-system]
requires = ["setuptools", "wheel", "setuptools-pipfile"]
build-backend = "setuptools.build_meta"

[tool.setuptools-pipfile]

[tool.setuptools.dynamic]
version = {attr = "thoth.package_extract.__version__"}
```

From my understand it looks like the Pipfile is not added to the sdist and then can not be found during the wheel build, is that correct ? Am I missing something at in my config or is it a bug ?

Thanks

**Comment by asyncon** [comment]
If dynamic generation of included files isn't performed by a plugin such as [setuptools_scm](https://github.com/pypa/setuptools_scm) then the Pipfile should be added to the sdist via [MANIFEST.in](https://packaging.python.org/en/latest/guides/using-manifest-in/).

**Comment by VannTen** [comment]
Thanks a lot :+1:
